name: Build Python Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Use the latest version of checkout

    - name: Set up Python
      uses: actions/setup-python@v5  # Use the latest version of setup-python
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pytest pytest-cov

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed tableGui.py

    - name: Upload executable
      uses: actions/upload-artifact@v4  # Update to v3
      with:
        name: python-executable
        path: output/tableGui.exe
