name: Build Python Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Use the latest version of checkout

    - name: Set up Python
      uses: actions/setup-python@v5  # Use the latest version of setup-python
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: PyInstaller Windows
    # You may pin to the exact commit or the version.
    # uses: JackMcKew/pyinstaller-action-windows@a8dee21ad01bbc7e7363d445bb632691b95ba057
    uses: JackMcKew/pyinstaller-action-windows@v0.1.2
    with:
      # Directory containing source code (optional requirements.txt).
      path: # default is src
          
        
   
